package ar.sessions.utils;

public enum ConfigurationCommands {
		EXIT,
		SET,
		DELETE,
		STATUS,
		TIME_LOGIN,
		CANT_LOGIN,
		BLACK_IP,
		RM_FILTER_DATE,
		RM_FILTER_SENDER,
		RM_FILTER_HEADER,
		RM_FILTER_CONTENT,
		RM_FILTER_SIZE,
		RM_FILTER_DISPOSITION,
		ORIGIN_SERVER,
		ORIGIN_SERVER_PORT,
		CONFIG_LISTENING_PORT,
		WELLCOME_LISTENING_PORT,
		STA_LISTENING_PORT,
		APP
}
